### ISSUE TITLE
It's not working for me. am i doing anything wrong?

### ISSUE THREAD

**Issue by jitendravyas** [muzix/ghost-s3#13]
storage: {
    active: 'ghost-s3',
    'ghost-s3': {
        accessKeyId: 'dvdggrtre45555345',
        secretAccessKey: '67565rhtrhtl;;'uyu',
        bucket: 'weblog-cdn',
        region: 'ap-southeast-1',
        assetHost: 'https://weblog-cdn.s3-ap-southeast-1.amazonaws.com/'
    }
},

**Comment by rwboyer** [comment]
@jitendravyas thanks, that did it.

**Comment by muzix** [comment]
@jitendravyas @rwboyer 
With symptoms as you said, i guess it because of S3 bucket's permission not being set to public by default. Thanks to @nsfmc, i just merge and update to 0.2.2.  May be it help resolve your issue.

**Comment by rwboyer** [comment]
@muzix thanks for the update... will try it out and let you know what happens but I do have a question. Unless I didn't explain what is happening clearly how exactly do those symptoms appear to you as a permission issue? Those fail hard and fast in my experience, also it's kinda hard to get the write/create part correct and the read part wrong. I have the access for that bucket set for user as wells everyone else completely open about six different ways as I was trying to debug this. Be happy to give you the bucket policies if you would like to see them.

**Comment by rwboyer** [comment]
@muzix @nsfmc 

Just took a look at the update... did you change anything but the readme? the assetHost url is certainly fine here it is:

http://test-ghost-heroku.s3-website-us-east-1.amazonaws.com/2015/Sep/dark_cover-1442667232553.jpg

works fine and those particular images were stored in the bucket via ghost. Here's a question: that giant number at the end, is that something "new" that ghost is tacking on for image uploads??  Maybe not super new but I've not taken notice to it before and it was not part of the original file name.

**Comment by rwboyer** [comment]
@muzix - just tested again, exact same symptoms as before. want to take a look at my configs and bucket policies?

**Comment by rwboyer** [comment]
@muzix 

running it in node debugger now. something strange is going on around:

return readFile(image.path)

in save a really odd and wrong looking path is in the image object like a real directory (/var/blah-blah/blah/blah/really-long-bunch-of-crap/) but the ACTUAL image is stored in the appropriate place on my S3 bucket. Not looking like a permission problem at all.

**Comment by jeewangue** [comment]
@jitendravyas @rwboyer 
I was suffering from the exactly same problem with you and I figured out the problem at last.
change the 'assetHost' in config.js file
'https://weblog-cdn.s3-ap-southeast-1.amazonaws.com/' to
'https://s3-ap-southeast-1.amazonaws.com/weblog-cdn/'
and it will work properly.

I think it'll be great to note on Readme.md to use Path style url for amazon s3.
Though longer than a month passed, I hope it helped you.

**Comment by rwboyer** [comment]
@jeewangue thanks for the update but...
changed url styles as you suggested and I get the same symptoms. Image uploads fine and stores correctly in S3 but the admin UI just sits there with the cat rocking back and forth as if it's still waiting for something after image progress bar is done. I am running Ghost 7.0

**Comment by jeewangue** [comment]
@rwboyer 
did you added bucket policy in aws console?
it should be like

```
{
    "Version": "2008-10-17",
    "Statement": [
        {
            "Sid": "AllowPublicRead",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::your-bucket-name/*"
        }
    ]
}
```

I granted whole permissions for s3 bucket to IAM User, and I also had to allow everyone to read bucket contents through this policy.
Can you capture the log file and share with me when you upload a image?
For reference, I'm using Ghost 7.1 now.

**Comment by rwboyer** [comment]
was about to update. the url format change did the trick but I had a typo -- so i had a bit of an itchy trigger finger in my first update. It works fine now and thank you... wonder why the other url format doesn't work?

**Comment by jeewangue** [comment]
http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html

I think the Virtual Hosted–Style url works if you set the bucket as static virtual hosting page.
I saw that option at the bucket properties settings.
as we did not set up that nor want to set up that, i think we should use path-style url
