### ISSUE TITLE
Update for Ghost 0.6 

### ISSUE THREAD

**Issue by ErisDS** [muzix/ghost-s3#2]
Hi there!

I'm just dropping by to let you know we'll be releasing Ghost 0.6 very shortly, which has some big changes around storage, so that you don't have to hack core any more to add a custom storage class like this one :)

Docs on how to do it are here (first pass, let me know if you  need anything else) https://github.com/TryGhost/Ghost/wiki/Using-a-custom-storage-module

The docs link back here as a good example of how to implement the `save` and `serve` methods :)

**Comment by muzix** [comment]
Hi,
Thank you for informing me. I will have a look and upgrade this soon.

**Comment by benwoodward** [comment]
+1 👍

**Comment by muzix** [comment]
Hi all,
Just updated 0.2.0 for new version of Ghost.

**Comment by benwoodward** [comment]
Awesome! Thanks a lot. :smile:
