### ISSUE TITLE
problem with S3 auth token

### ISSUE THREAD

**Issue by shea256** [muzix/ghost-s3#6]
Hi there, I'm having an issue with ghost-s3 that's essentially what's reported here:

https://github.com/cobyism/ghost-on-heroku/issues/20

I even tested it this with AWS root credentials and it doesn't work, so I know it's not a token policy thing.

Thoughts?

Thanks!

**Comment by shea256** [comment]
Please ignore this, as the issue has already been resolved, as you can see here:

https://github.com/cobyism/ghost-on-heroku/issues/20#issuecomment-114158359

I'll close this issue.

**Comment by muzix** [comment]
Nevermind, glad to hear your problem solved. If there is any mistake in this repo documentation, pls let me know :+1:
